### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by moakes010** [optilude/jira-cycle-extract#7]
Currently using python 3.6.1 and was able to get the package working with some minor tweaks (at least for the cfd charting).  There weren't that many print statements so I avoided appending 'from __future__ import print_function' to the modules and just explicitly  used print() in all instances. 

In the query.py module, python3 filter objects don't have the len method. The simplest fix is to cast filter to list.

For cycletime.py in the cycle_data function, I had to modify the series dtype from 'string' to 'object' since python 3 makes a distinction between binary and text data.

**Comment by dcuestac** [comment]
You can run it using Py2.7 or the Docker image should work too

**Comment by optilude** [comment]
This package has been superseded by https://github.com/DeloitteDigitalUK/jira-agile-metrics which runs on python 3.
